//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_SUBJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPLICANT_SUBJECT()
        {
            this.ACADEMIC_DETAILS = new HashSet<ACADEMIC_DETAILS>();
        }
    
        public long ApplicantSubjectId { get; set; }
        public int ExamId { get; set; }
        public long ApplicantId { get; set; }
        public short SubJectId { get; set; }
        public int Score { get; set; }
        public short GradeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACADEMIC_DETAILS> ACADEMIC_DETAILS { get; set; }
        public virtual APPLICANT APPLICANT { get; set; }
        public virtual EXAM EXAM { get; set; }
        public virtual GRADE GRADE { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
        public virtual SUBJECT SUBJECT1 { get; set; }
    }
}
