//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPLICANT()
        {
            this.APPLICANT_SUBJECT = new HashSet<APPLICANT_SUBJECT>();
            this.EXAM = new HashSet<EXAM>();
            this.STUDENT = new HashSet<STUDENT>();
        }
    
        public long ApplicantId { get; set; }
        public long AppliedBy { get; set; }
        public int FirstProgrammeId { get; set; }
        public Nullable<int> SecondProgrammeId { get; set; }
        public byte EntryTypeId { get; set; }
        public bool IsPending { get; set; }
        public long AcademicDetailsId { get; set; }
        public long ModeOfAdmissionId { get; set; }
        public long AdmissionStatusId { get; set; }
        public int SessionId { get; set; }
        public int SemesterId { get; set; }
        public bool IsAdmitted { get; set; }
        public bool IsRejected { get; set; }
        public Nullable<long> AdmittedBy { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public string Remark { get; set; }
        public int LevelId { get; set; }
        public byte SchoolId { get; set; }
    
        public virtual ACADEMIC_DETAILS ACADEMIC_DETAILS { get; set; }
        public virtual ADMISSION_STATUS ADMISSION_STATUS { get; set; }
        public virtual ENTRY_TYPE ENTRY_TYPE { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual PERSON PERSON1 { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual PROGRAMME PROGRAMME1 { get; set; }
        public virtual SCHOOL SCHOOL { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICANT_SUBJECT> APPLICANT_SUBJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAM> EXAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT> STUDENT { get; set; }
    }
}
