//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUS_DESCRIPTION
    {
        public long BusDecriptionId { get; set; }
        public long ApplicantId { get; set; }
        public string BusNumber { get; set; }
        public string DriversName { get; set; }
        public string DriversPhoneNumber { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
