//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTINUOUS_EDUCATION
    {
        public long ContinuousEducationId { get; set; }
        public long MaritalStatusId { get; set; }
        public long EmploymentStatusId { get; set; }
        public string Occupation { get; set; }
    }
}
