//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSTEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOSTEL()
        {
            this.HOSTEL_BLOCK = new HashSet<HOSTEL_BLOCK>();
            this.HOSTEL_PROGRAMME_ACCESS = new HashSet<HOSTEL_PROGRAMME_ACCESS>();
            this.ROOM = new HashSet<ROOM>();
        }
    
        public int HostelId { get; set; }
        public string Name { get; set; }
        public int ModuleId { get; set; }
        public short HostelTypeId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsRemoved { get; set; }
        public short NumberOfBlocks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSTEL_BLOCK> HOSTEL_BLOCK { get; set; }
        public virtual HOSTEL_TYPE HOSTEL_TYPE { get; set; }
        public virtual MODULE MODULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSTEL_PROGRAMME_ACCESS> HOSTEL_PROGRAMME_ACCESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROOM> ROOM { get; set; }
    }
}
