//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAGE()
        {
            this.PAGE_ACTION = new HashSet<PAGE_ACTION>();
            this.ROLE_PAGE_RIGHT = new HashSet<ROLE_PAGE_RIGHT>();
        }
    
        public int PageId { get; set; }
        public string Name { get; set; }
        public string PageUrl { get; set; }
        public string PageElementId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGE_ACTION> PAGE_ACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLE_PAGE_RIGHT> ROLE_PAGE_RIGHT { get; set; }
    }
}
