//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGE_ACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAGE_ACTION()
        {
            this.USER_PAGE_ACTION = new HashSet<USER_PAGE_ACTION>();
        }
    
        public int PageActionId { get; set; }
        public string ActionName { get; set; }
        public string ActionElementId { get; set; }
        public int PageId { get; set; }
    
        public virtual PAGE PAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_PAGE_ACTION> USER_PAGE_ACTION { get; set; }
    }
}
