//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_PAGE_RIGHT
    {
        public int RolePageRightId { get; set; }
        public string RightName { get; set; }
        public int RoleId { get; set; }
        public int ModuleId { get; set; }
        public int PageId { get; set; }
    
        public virtual MODULE MODULE { get; set; }
        public virtual PAGE PAGE { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
