//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROOM()
        {
            this.BUNK = new HashSet<BUNK>();
            this.STUDENT_HOSTEL_ROOM_BUNK = new HashSet<STUDENT_HOSTEL_ROOM_BUNK>();
        }
    
        public int RoomId { get; set; }
        public string RoomNumber { get; set; }
        public int HostelId { get; set; }
        public int BlockId { get; set; }
        public bool IsEnabled { get; set; }
        public int NumberOfBunks { get; set; }
        public bool IsRemoved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUNK> BUNK { get; set; }
        public virtual HOSTEL HOSTEL { get; set; }
        public virtual HOSTEL_BLOCK HOSTEL_BLOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_HOSTEL_ROOM_BUNK> STUDENT_HOSTEL_ROOM_BUNK { get; set; }
    }
}
