//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.STUDENT_HOSTEL_ROOM_BUNK = new HashSet<STUDENT_HOSTEL_ROOM_BUNK>();
            this.STUDENT_SESSION_DETAIL = new HashSet<STUDENT_SESSION_DETAIL>();
            this.STUDENT_SESSION_DETAIL1 = new HashSet<STUDENT_SESSION_DETAIL>();
        }
    
        public long StudentId { get; set; }
        public Nullable<long> ApplicantId { get; set; }
        public string RegNumber { get; set; }
        public int ProgrammeId { get; set; }
        public Nullable<int> ProgrammeId2 { get; set; }
        public int DepartmentId { get; set; }
        public long CurrentStudentSessionDetailId { get; set; }
        public byte SchoolId { get; set; }
    
        public virtual APPLICANT APPLICANT { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual PROGRAMME PROGRAMME1 { get; set; }
        public virtual SCHOOL SCHOOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_HOSTEL_ROOM_BUNK> STUDENT_HOSTEL_ROOM_BUNK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_SESSION_DETAIL> STUDENT_SESSION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_SESSION_DETAIL> STUDENT_SESSION_DETAIL1 { get; set; }
        public virtual STUDENT_SESSION_DETAIL STUDENT_SESSION_DETAIL2 { get; set; }
    }
}
