//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_HOSTEL_ROOM_BUNK
    {
        public long StudentBunkId { get; set; }
        public int HostelId { get; set; }
        public long BunkId { get; set; }
        public int RoomId { get; set; }
        public int BlockId { get; set; }
        public long StudentId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public long EnteredBy { get; set; }
        public int SemesterId { get; set; }
        public int SessionId { get; set; }
        public bool IsRemoved { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateRemoved { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual BUNK BUNK { get; set; }
        public virtual HOSTEL_BLOCK HOSTEL_BLOCK { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ROOM ROOM { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
