//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_SESSION_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_SESSION_DETAIL()
        {
            this.STUDENT2 = new HashSet<STUDENT>();
        }
    
        public long StudentSessionDetailId { get; set; }
        public long StudentId { get; set; }
        public int SessionId { get; set; }
        public int SemesterId { get; set; }
        public int LevelId { get; set; }
        public System.DateTime DateEntered { get; set; }
    
        public virtual LEVEL LEVEL { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual STUDENT STUDENT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT> STUDENT2 { get; set; }
    }
}
