//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SOLUTION.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_MODULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_MODULE()
        {
            this.USER_MODULE_ROLE = new HashSet<USER_MODULE_ROLE>();
            this.USER_PAGE_ACTION = new HashSet<USER_PAGE_ACTION>();
        }
    
        public int UserModuled { get; set; }
        public long PersonId { get; set; }
        public int ModuleId { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual MODULE MODULE { get; set; }
        public virtual PERSON PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_MODULE_ROLE> USER_MODULE_ROLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_PAGE_ACTION> USER_PAGE_ACTION { get; set; }
    }
}
